### ISSUE TITLE
Calibration issue about calibration.txt

### ISSUE THREAD

**Issue by TerryHoQvQ** [MarekKowalski/LiveScan3D#35]
Hi,

Thanks for your nice share first! I am using two kinects and one marker to calibrate, then get the file 'calibration.txt' on the 'Server' computer.I want to know the extrinsics and intrinsics，but I think the file only provides the extrinsics(T,R).I don't know if I understand it wrong. Cloud you tell me the meaning of the parameters inside and how to get the intrinsics?
![image](https://user-images.githubusercontent.com/44295681/53961538-cc5fc500-4123-11e9-9159-c4eeacbc6e96.png)

**Comment by MarekKowalski** [comment]
Hi,

You are correct that the file only provides the extrinsics.
The parameters inside are:
 - translation vector
 - rotation matrix
 - id of the marker used for calibration
 - a boolean indicated whether calibration was successful
You can also see the code that loads the file on lines 133-151 [here](https://github.com/MarekKowalski/LiveScan3D/blob/bd969205c226b10f4769488e76f98c6d144c8dc9/src/LiveScanClient/calibration.cpp).

As for the intrinsics you can obtain them from the Kinect SDK.

Thanks,

Marek

**Comment by TerryHoQvQ** [comment]
Hi,

Thank you for your reply so quickly.The T,R means the correlation between world coordinates and camera coordinates，right? I have two Kinects that use the same marker to calibrate, but why did I get only one calibration result?

**Comment by MarekKowalski** [comment]
The calibration results are saved by the client app, which receives data from only a single Kienct.
