### ISSUE TITLE
Q: Camera cannot be successfully calibrated

### ISSUE THREAD

**Issue by JohnnistWangc** [MarekKowalski/LiveScan3D#42]
![Capture](https://user-images.githubusercontent.com/29157391/68728374-234a6200-0602-11ea-88bd-b5e70ef14315.PNG)

**Comment by MarekKowalski** [comment]
Hi, did you look at the manual in the docs? Did you print the markers and put them in the scene?

Marek

**Comment by JohnnistWangc** [comment]
Thank you very much for your help. The following picture is a reconstruction of the school bag. 
![bag](https://user-images.githubusercontent.com/29157391/69300298-bceec080-0c4d-11ea-9880-c6e3ff544be1.JPG)
The effect is good, but there are still some problems. The frame rate collected when rebuilding the dynamic object is too small, causing the image to be ghosted, and whether the slot can be further optimized ?

**Comment by MarekKowalski** [comment]
What framerate do you see? (it's the number on top of the live view window).
Are you compiling in Debug or Release mode? If everything is compiled in release you should get 25-30fps.

**Comment by JohnnistWangc** [comment]
Yes, but I can only get less than 10fps, and I am using the release version, not the debug version. I checked the "filtering" option.

**Comment by MarekKowalski** [comment]
The filtering can slow things down. How fast is it without filtering?
The filtering speed depends on the number of points, so limiting the volume you are using (through settings) will speed things up.
You can also play around with the N neigbours parameter to speed the filtering up.
