### ISSUE TITLE
calibration.txt

### ISSUE THREAD

**Issue by cfx3120180310** [MarekKowalski/LiveScan3D#43]
Thank you in advance for sharing this great work! Great help for me.
I have obtained a translation vector and rotation matrix from the sensor coordinate system to the landmark coordinate system, but I don't know how to convert it into a Matrix4 × 4 matrix in Unity3D.
![Uploading image.png…]()
So, could you help me get the Matrix 4 × 4 in unity3D, or the rotation angle along the x, y, and z axes?
I would appreciate it if you could make some suggestions.

**Comment by futuraspace** [comment]
Did you acomplish the transformation??
