### ISSUE TITLE
How to Converting KinectServer Csharp to C++ using Winsock2

### ISSUE THREAD

**Issue by kirubhakinect** [MarekKowalski/LiveScan3D#5]
Currently i'm working in Passing KinectV2 streams between different system. Existing system was developed using c++,openGL both Client and server. I think this repository is better than my existing system. So i  am willing to migrate everything to my source. Please help me to converting KinectServer Csharp to C++.and suggest me what are the steps needed to creating Winsock Receiver side.

Thanks ,
Kirubha

**Comment by MarekKowalski** [comment]
Hi,
Converting the entire KinectServer to C++ would take a lot of work. I suggest that you only migrate the communication part, which is located in KinectSocket, and integrate it with your current system.
As for the winsock, I suggest you use the same C++ socket library used by the KinectClient, as it is very easy to use. 

If you have more specific questions, let me know, preferably by email.

Best,

Marek
