### ISSUE TITLE
Problems about showing .ply in LiveScanPlayer.exe

### ISSUE THREAD

**Issue by ERICXUCHI** [MarekKowalski/LiveScan3D#69]
Hi, team. I have saved the .ply files, but when I started the player and selected the files, the current number is changing from 0 to 50 frame but nothing shows on the screen, should there be a 3D player showed? Or how I can do to solve this problem?

2 Windows 10 + 2 Azure Kinects

the screen is like below:
![image](https://github.com/MarekKowalski/LiveScan3D/assets/57583292/61c969c0-aeac-4f1a-a777-31419113981d)

**Comment by ChristopherRemde** [comment]
You just need to click on the "Show live" button

**Comment by ERICXUCHI** [comment]
Thanks for your reply! Yeah, I tried your suggestion but nothing happened. The FPS is always 0.
![image](https://github.com/MarekKowalski/LiveScan3D/assets/57583292/3e82bf71-6770-4209-9a38-1d1d5272bc66)

What's more, when I tried to 'show live' in the server.exe, the FPS is about 15 on average (with T500 GPU) and nothing shows on the screen.
And when I tried to save .ply, all .ply is 1kb, which I thought I did not save them successfully.
Do you ever encounter such problems? Or how I could do to solve it😂

**Comment by ChristopherRemde** [comment]
Hm it could be that you actually didn't record anything. When you can't see anything in the Live Preview on the server, this also means no data is being recorded. How large is your .bin file?

The FPS being low is normal, that's due to the limited bandwith.

**Comment by ERICXUCHI** [comment]
I have used two Azure Kinects so there is perhaps no .bin file. 

 Are there any alternative solutions? 😣

**Comment by ChristopherRemde** [comment]
There should be a .bin file in the LiveScan3D/bin/ folder called recording_XXX.bin after you've recorded a capture. Do you see anything there?

**Comment by ERICXUCHI** [comment]
Yeah, I saw it under /bin folder. But the .bin file is also about 1-5 kb, there may be something wrong during recording.

**Comment by ERICXUCHI** [comment]
What's more, I cannot see anything when I click 'show live' in the server.exe, even though the FPS ~30.

However, if I did not generate the release version and just click 'run' in the visual studio 2019, the 'show live' runs correctly and can show the images. Do you ever encounter this problem?

**Comment by ChristopherRemde** [comment]
I see you started a new issue. Could you close this one?

**Comment by ERICXUCHI** [comment]
Yeah, no problem. I found that in this repo "https://github.com/BuildingVolumes/LiveScan3D" it works. Thanks a lot!
