### ISSUE TITLE
Show nothing when I click 'show live' in the server.exe

### ISSUE THREAD

**Issue by ERICXUCHI** [MarekKowalski/LiveScan3D#70]
Hi, guys, I cannot see anything when I click 'show live' in the server.exe, even though the FPS ~30.

<img width="601" alt="Snipaste_2023-08-16_11-06-31" src="https://github.com/MarekKowalski/LiveScan3D/assets/57583292/ff87c15b-5920-4142-b549-f2adf7c58c83">

However, if I did not generate the release version and just click 'run' in the visual studio 2019, the 'show live' runs correctly and can show the images. Do you ever encounter this problem?

<img width="600" alt="919a2bf51d9d43a8aa0264a795c93c6" src="https://github.com/MarekKowalski/LiveScan3D/assets/57583292/f1fb6063-83f5-43db-a38f-d339e9396a44">

**Comment by ERICXUCHI** [comment]
Hi, I found it solves in this repo "https://github.com/BuildingVolumes/LiveScan3D".
Maybe you can modify this AzureKinect branch.
However, in the new repo, I found that my two azure kinects recorded two different view of .bin file and they are not complete in one PC. Do you know how to solve it?

**Comment by ChristopherRemde** [comment]
Yes that is the new version of LiveScan we're working on right now and will eventually replace this version. However it's still work in progress and probably contains some bugs

Please open an issue in the new Repository for any questions about the new version

**Comment by ERICXUCHI** [comment]
Yeah, but it seems that I cannot find the 'issues' section in the new Repository. :(

![image](https://github.com/MarekKowalski/LiveScan3D/assets/57583292/8eb78132-ecc3-4e16-a73d-a540f8a93f94)

**Comment by ChristopherRemde** [comment]
Im very sorry, I forgot to enable it, please try again now!

**Comment by ERICXUCHI** [comment]
Okay, then I would close this issue. Thanks for your patience and support!
